name: Auto Test

on:
  push:
    paths:
      - 'solutions/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'solutions/**'
      - 'tests/**'

jobs:
  detect-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        if: contains(github.event.head_commit.message, '.java') || contains(github.event.head_commit.message, 'Test.java')
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Python
        if: contains(github.event.head_commit.message, '.py')
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python Tests
        if: contains(github.event.head_commit.message, '.py')
        run: |
          python tests/test.py > python_test_output.txt
          cat python_test_output.txt
          if grep -q "failed" python_test_output.txt; then
            echo "One or more Python test cases failed."
            exit 1
          fi

      - name: Compile Java Code
        if: contains(github.event.head_commit.message, '.java')
        run: |
          javac solutions/Solution.java tests/Test.java

      - name: Run Java Tests
        if: contains(github.event.head_commit.message, '.java')
        run: |
          java -cp . tests.Test > java_test_output.txt
          cat java_test_output.txt
          if grep -q "failed" java_test_output.txt; then
            echo "One or more Java test cases failed."
            exit 1
          fi

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            *.txt
