- name: Determine LANGUAGES
        run: |
          LANGUAGES=""
          for f in ${{ env.CHANGED_FILES }}; do
            case "$f" in
              *.c)    LANGUAGES="$LANGUAGES C" ;;
              *.cpp)  LANGUAGES="$LANGUAGES CPP" ;;
              *.java) LANGUAGES="$LANGUAGES JAVA" ;;
              *.py)   LANGUAGES="$LANGUAGES PY" ;;
            esac
          done
          echo "CHANGED_LANGUAGES=$LANGUAGES" >> $GITHUB_ENV
          echo "→ Detected LANGUAGES=${{ env.CHANGED_LANGUAGES }}"

      - name: Setup Java
        if: contains(env.CHANGED_LANGUAGES, 'JAVA')
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Python
        if: contains(env.CHANGED_LANGUAGES, 'PY')
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Compile & Run C Tests
        if: contains(env.CHANGED_LANGUAGES, 'C')
        run: |
          set -euo pipefail
          gcc solutions/Solution.c tests/test.c -o test_c
          ./test_c | tee c_test_output.txt

      - name: Compile & Run C++ Tests
        if: contains(env.CHANGED_LANGUAGES, 'CPP')
        run: |
          set -euo pipefail
          g++ tests/test.cpp -o test_cpp
          ./test_cpp | tee cpp_test_output.txt

      - name: Compile & Run Java Tests
        if: contains(env.CHANGED_LANGUAGES, 'JAVA')
        run: |
          set -euo pipefail
          javac solutions/Solution.java tests/Test.java
          java -cp . tests.Test | tee java_test_output.txt

      - name: Run Python Tests
        if: contains(env.CHANGED_LANGUAGES, 'PY')
        run: |
          set -euo pipefail
          python3 tests/test.py | tee python_test_output.txt
