name: Run Code Tests

on:
  push:
    paths:
      - "solutions/**"
  pull_request:
    paths:
      - "tests/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect Changed Solution File
        id: detect-file
        run: |
          FILE=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^solutions/' | head -n 1)
          echo "Changed file: $FILE"
          echo "CHANGED_FILE=$FILE" >> $GITHUB_ENV

          EXT="${FILE##*.}"
          if [[ "$EXT" == "c" ]]; then
            echo "LANGUAGE=C" >> $GITHUB_ENV
          elif [[ "$EXT" == "cpp" ]]; then
            echo "LANGUAGE=C++" >> $GITHUB_ENV
          elif [[ "$EXT" == "py" ]]; then
            echo "LANGUAGE=Python" >> $GITHUB_ENV
          elif [[ "$EXT" == "java" ]]; then
            echo "LANGUAGE=Java" >> $GITHUB_ENV
          else
            echo "Unsupported language: $EXT"
            exit 1
          fi

      - name: Install Dependencies
        run: |
          sudo apt update
          if [[ "$LANGUAGE" == "C" ]]; then sudo apt install -y gcc;
          elif [[ "$LANGUAGE" == "C++" ]]; then sudo apt install -y g++;
          elif [[ "$LANGUAGE" == "Java" ]]; then sudo apt install -y openjdk-17-jdk;
          elif [[ "$LANGUAGE" == "Python" ]]; then sudo apt install -y python3;
          fi

      - name: Run C Test
        if: env.LANGUAGE == 'C'
        run: |
          gcc tests/test.c -o runner
          ./runner

      - name: Run C++ Test
        if: env.LANGUAGE == 'C++'
        run: |
          g++ tests/test.cpp -o runner
          ./runner

      - name: Run Python Test
        if: env.LANGUAGE == 'Python'
        run: python3 tests/test.py

      - name: Run Java Test
        if: env.LANGUAGE == 'Java'
        run: |
          javac tests/Test.java
          java -cp tests Test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_results.log
